<div class="welcome-panel" id="welcome-panel">
    <div class="welcome-panel-content">
        <h3><span class="glyphicon glyphicon-tags"></span><?php _e('License', 'wptkt'); ?></h3>
        <p class="about-description">
            <?php echo $wptktAdmin->getVersion(); ?>
        </p>
    </div>
</div>
<p>&nbsp;</p>
<h3><?php _e('Enter your License here:', 'wptkt'); ?></h3>
<form action="admin.php?page=wptkt&mod=license&action=save-license" method="post">
    <table class="form-table">
        <tbody>
            <tr>
                <th scope="row">
                    <label for="blogname"><?php _e('Email', 'wptkt'); ?></label>
                </th>
                <td>
                    <input type="text" class="regular-text" name="license-email" value="<?php echo get_option('wptkt_license_email'); ?>" />
                </td>
            </tr>
            <tr>
                <th scope="row">
                    <label for="blogname"><?php _e('License Key', 'wptkt'); ?></label>
                </th>
                <td>
                    <input type="text" class="regular-text" name="license-key" value="<?php echo get_option('wptkt_license_key'); ?>" />
                </td>
            </tr>
        </tbody>
    </table>
    <p class="submit">
        <input type="submit" value="<?php _e('Save License', 'wptkt'); ?>" class="button-primary">
    </p>
</form>
<p class="description">
    <?php _e('Get an additional license key on <a target="_blank" href="http://woocommerce-klick-tipp.com">woocommerce-klick-tipp.com</a>', 'wptkt'); ?>.
</p>