<div class="welcome-panel" id="welcome-panel">
    <div class="welcome-panel-content">
        <h3><span class="glyphicon glyphicon-tags"></span><?php _e('License', 'wptkt'); ?></h3>
        <p class="about-description">
            <?php _e('Free Version, <a href="http://woocommerce-klick-tipp.com/wptokt-verkaufsseite/?utm_campaign=plugin-backend-opensource-eng" target="_blank">Upgrade to Pro to get full data sync</a>', 'wptkt'); ?>
        </p>
    </div>
</div>
<div class="container clearfix">
    <div class="col-fifty-fifty">
        <h3><?php _e('Get Premium License', 'wptkt'); ?></h3>
        <p style="margin-right: 20px;"><?php _e('To activate the Premium Version you need to download the free/Premium Plugin Version here:', 'wptkt'); ?></p>
        <p style="margin-right: 20px;"><?php _e('<a href="http://woocommerce-klick-tipp.com/wptokt-verkaufsseite/?utm_campaign=plugin-backend-opensource-eng" target="_blank" class="button">free/Premium Version</a>', 'wptkt'); ?></p>
		<p style="margin-right: 20px;"><?php _e('After Download: Please deinstall this version and install the downloaded version.<br>No data will be lost.', 'wptkt'); ?></p>
    </div>
    <div class="col-fifty-fifty">
        <h3><?php _e('Free Member Area', 'wptkt'); ?></h3>
        <p><?php _e('Use our free member area to get video tutorials, downloads and exchange with other users.', 'wptkt'); ?></p>        <p>
        </p><p><?php _e('<a href="http://woocommerce-klick-tipp.com/?utm_campaign=plugin-backend-opensource-eng" target="_blank" class="button">Get access now</a>', 'wptkt'); ?></p>        <p>
        </p>
    </div>
</div>