<table cellspacing="0" class="wptkt_table widefat">
    <thead>
        <tr>
            <th><?php _e('Check the software requirements', 'wptkt'); ?></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><?php _e('check your software requirements to use all of the plugins functionality.', 'wptkt'); ?></td>
        </tr>
        <tr>
            <td>
                <table width="100%" border="0">
                    <tr>
                        <th scope="row"><?php _e('WooCommerce is activated', 'wptkt'); ?></th>
                        <td><?php echo '<img src="'.WP_TO_KLICK_TIPP_URL.'/assets/img/'.(WC_ACTIVE_FLAG ? 'accepted_32.png' : 'cancel_32.png').'" alt=""/>'; ?></td>
                    </tr>
                    <tr>
                        <th scope="row"><?php _e('PHP version', 'wptkt'); echo '&nbsp;('.phpversion().')'; ?></th>
                        <td><?php
        $iPhpVersion = preg_replace("/[^0-9]/","",substr(phpversion(),0,3)); // use phpversion() for server with PHP< 5.3
		echo '<img src="'.WP_TO_KLICK_TIPP_URL.'/assets/img/'.($iPhpVersion < 54 ? 'cancel_32.png' : 'accepted_32.png').'" alt=""/>';
		?>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row"><?php _e('IonCube Loader<br >(you need it to run our premium version)', 'wptkt'); ?></th>
                        <td><?php $run_ioncubetesterplus = new ioncubetester(); unset($run_ioncubetesterplus); ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    </tbody>
</table>
