<form action="admin.php?page=wptkt&mod=cron-setting&action=save-cron-setting" method="post">
    <?php if (!$wptktAdmin->isPremium()) : ?>
        <div class="updated">
            <p>
                <?php _e('You want to sync WooCommerce products, categories, order status updates... ? Get a "WP to Klick-Tipp" premium license.', 'wptkt'); ?>
            </p>
        </div>
    <?php endif; ?>
    <table cellspacing="0" class="wptkt_table widefat">
        <thead>
            <tr>
                <th colspan="2"><?php _e('Cron Settings', 'wptkt'); ?></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <?php _e('Last data sync to Klick-Tipp', 'wptkt'); ?>
                </td>
                <td>
                    <p>
                        <?php echo $wptktAdmin->getLastSync(); ?>
                    </p>
                </td>
            </tr>
            <?php if (function_exists('woocommerce_get_page_id')) : ?>
            <tr>
                <td>
                    <?php _e('Reset Sync Time', 'wptkt'); ?>
                </td>
                <td>
                    <p>
                        <a class="button" href="admin.php?page=wptkt&mod=cron-setting&action=reset-sync"><?php _e('Reset Sync Time Button', 'wptkt'); ?></a>
                    </p>
                </td>
            </tr>
            <?php endif; ?>
            <tr>
                <td>
                    <?php _e('Use WordPress-Cron', 'wptkt'); ?>
                </td>
                <td>
                    <p>
                        <label><input type="checkbox" name="wptkt_wordpress_cron" value="1" <?php echo get_option('wptkt_wordpress_cron')=='1'?'checked':''; ?> /> <?php _e('Enabled', 'wptkt'); ?></label>
                    </p>
                    <p>
                        <span class="description"><?php _e('Enable this option to use the build-in WordPress-Cron.', 'wptkt'); ?></span>
                    </p>
                </td>
            </tr>
            <tr>
                <td><?php _e('Trigger cron manually', 'wptkt'); ?></td>
                <td>
                    <p>
                        <a class="button show-activity-indicator" href="admin.php?page=wptkt&mod=cron-setting&action=trigger-cron"><?php _e('Run Cron', 'wptkt'); ?></a> <img src="<?php echo WP_TO_KLICK_TIPP_URL; ?>/assets/img/ajax-loader.gif" alt="" style="display: none;" />
                    </p>
                </td>
            </tr>
        </tbody>
    </table>
    <p class="submit">
        <input type="submit" value="<?php _e('Save Changes', 'wptkt'); ?>" class="button-primary">
    </p>
</form>